account/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings

from django.contrib.auth import views as auth_views
app_name = 'account'


urlpatterns = [
    url(r'^login/$',auth_views.LoginView.as_view(template_name="account/login.html"),name='auth_login'),
    url(r'^logout/$',auth_views.LogoutView.as_view(template_name="account/logout.html"), name='auth_logout'),
]

crawler/urls.py
from django.contrib import admin
# from django.urls import path
from django.conf.urls import url,include


urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^account/',include('account.urls', namespace='account')),
    url(r'^function/',include('function.urls',namespace='function')),
]

function/urls.py
from  django.conf.urls import url
from . import views
app_name = 'function'

urlpatterns = [
    url(r'^index/',views.index,name='index'),
    url(r'^count/',views.count,name='count'),
    url(r'^count1/',views.count1,name='count1'),
    url(r'^low_unprocessed_list_html/',views.low_unprocessed_list_html,name='low_unprocessed_list_html'),
    url(r'^high_unprocessed_list_html/',views.high_unprocessed_list_html,name='high_unprocessed_list_html'),
    url(r'^low_processed_list_html/',views.low_processed_list_html,name='low_processed_list_html'),
    url(r'^high_processed_list_html/',views.high_processed_list_html,name='high_processed_list_html'),
    url(r'^comment_list/',views.comment_list,name='comment_list'),
    url(r'^comment_content/',views.comment_content,name='comment_content'),
    url(r'^comment_content_high_processed/',views.comment_content_high_processed,name='comment_content_high_processed'),
    url(r'^comment_content_high_unprocessed/',views.comment_content_high_unprocessed,name='comment_content_high_unprocessed'),
    url(r'^comment_content_low_processed/',views.comment_content_low_processed,name='comment_content_low_processed'),
    url(r'^comment_content_low_unprocessed/',views.comment_content_low_unprocessed,name='comment_content_low_unprocessed'),
    url(r'^submit_newscore/',views.submit_newscore,name='submit_newScore'),
    url(r'^send_message/',views.send_message,name='send_message'),
    url(r'^changeitems/',views.changeitems,name='changeitems'),
    url(r'^admin/index$',views.admin,name='admin'),
    url(r'^save_train/', views.save_train, name='save_train'),
    url(r'^precision/', views.precision, name='precision'),
    url(r'^sys_all/', views.sys_all, name='sys_all'),
]

function/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=80)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class Comments(models.Model):
    comment_id = models.AutoField(primary_key=True)
    content = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    sys_score = models.FloatField(blank=True, null=True)
    arti_score = models.FloatField(blank=True, null=True)
    catch_time = models.DateField(blank=True, null=True)
    comment_time = models.DateField(blank=True, null=True)
    is_scored = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'comments'


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.PositiveSmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'

function/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from .models import *
from django.conf import settings  # 导入配置文件
from django.core.mail import send_mail  # 导入发送邮件的包
import json
from snownlp import sentiment,SnowNLP



@csrf_exempt
def count(request):
    # 低分未处理
    low_unprocesseds = Comments.objects.filter(sys_score__lte=0.5,is_scored=0)
    low_unprocessed = 0
    for i in low_unprocesseds:
        low_unprocessed = low_unprocessed + 1
    # 低分已处理
    low_processeds = Comments.objects.filter(sys_score__lte=0.5, is_scored=1)
    low_processed = 0
    for i in low_processeds:
        low_processed = low_processed + 1
    # 高分未处理
    high_unprocesseds = Comments.objects.filter(sys_score__gt=0.5, is_scored=0)
    high_unprocessed = 0
    for i in high_unprocesseds:
        high_unprocessed = high_unprocessed + 1
    # 高分已处理
    high_processeds = Comments.objects.filter(sys_score__gt=0.5, is_scored=1)
    high_processed = 0
    for i in high_processeds:
        high_processed = high_processed + 1
    # print({"low_unprocessed": low_unprocessed, "low_processed": low_processed, "high_unprocessed": high_unprocessed,
    #      "high_processed": high_processed, "msg": "success"})

    return JsonResponse({"low_unprocessed":low_unprocessed,"low_processed":low_processed,
                         "high_unprocessed": high_unprocessed,"high_processed":high_processed,"msg":"success"})
@csrf_exempt
def index(request):
    return render(request,"function/index.html")

@csrf_exempt
def low_unprocessed_list_html(request):
    return render(request,"function/comment_list_low_unprocessed.html")

@csrf_exempt
def high_unprocessed_list_html(request):
    return render(request,"function/comment_list_high_unprocessed.html")

@csrf_exempt
def low_processed_list_html(request):
    return render(request,"function/comment_list_low_processed.html")

@csrf_exempt
def high_processed_list_html(request):
    return render(request,"function/comment_list_high_processed.html")

@csrf_exempt
def comment_content_low_processed(request):
    return render(request,"function/comment_content_low_processed.html")

@csrf_exempt
def comment_content_low_unprocessed(request):
    return render(request,"function/comment_content_low_unprocessed.html")

@csrf_exempt
def comment_content_high_processed(request):
    return render(request,"function/comment_content_high_processed.html")

@csrf_exempt
def comment_content_high_unprocessed(request):
    return render(request,"function/comment_content_high_unprocessed.html")

@csrf_exempt
def admin(request):
    return render(request,"admin/index.html")

@csrf_exempt
def comment_list(request):

    library = request.POST.get("library")
    process = request.POST.get("process")
    page_current = int(request.POST.get("page_current"))
    start = (page_current-1)*10
    end = (page_current * 10)

    low_unprocesseds = Comments.objects.filter(sys_score__lte=0.5, is_scored=0)
    low_unprocessed = 0
    for i in low_unprocesseds:
        low_unprocessed = low_unprocessed + 1
    # 低分已处理
    low_processeds = Comments.objects.filter(sys_score__lte=0.5, is_scored=1)
    low_processed = 0
    for i in low_processeds:
        low_processed = low_processed + 1
    # 高分未处理
    high_unprocesseds = Comments.objects.filter(sys_score__gt=0.5, is_scored=0)
    high_unprocessed = 0
    for i in high_unprocesseds:
        high_unprocessed = high_unprocessed + 1
    # 高分已处理
    high_processeds = Comments.objects.filter(sys_score__gt=0.5, is_scored=1)
    high_processed = 0
    for i in high_processeds:
        high_processed = high_processed + 1

    # 低分未处理

    if library == 'low' and process == 'unprocessed':
        low_un_list = []
        low_unprocesseds = Comments.objects.filter(sys_score__lte=0.5, is_scored=0)
        for i in low_unprocesseds[start:end]:
            low_un_list.append({"id": i.comment_id,"catch_time": i.catch_time,"comment_time": i.comment_time,
                                "final_score": i.sys_score})
        pages = (low_unprocessed // 10)

        if low_unprocessed % 10 != 0:
            pages = pages +1
        return JsonResponse({"msg": "success", "items": low_un_list, "pages": pages})

    # 低分已处理

    if library == 'low' and process == 'processed':
        low_list = []
        low_processeds = Comments.objects.filter(sys_score__lte=0.5, is_scored=1)
        for i in low_processeds[start:end]:
            low_list.append({"id": i.comment_id,"catch_time": i.catch_time,"comment_time": i.comment_time,
                             "final_score": i.sys_score})
        pages = (low_processed // 10)

        if low_processed % 10 != 0:
            pages = pages +1
        return JsonResponse({"msg": "success", "items": low_list, "pages": pages})

    # 高分未处理
    if library == 'high' and process == 'unprocessed':
        high_un_list = []
        high_unprocesseds = Comments.objects.filter(sys_score__gt=0.5, is_scored=0)
        for i in high_unprocesseds[start:end]:
            high_un_list.append({"id": i.comment_id,"catch_time": i.catch_time,"comment_time": i.comment_time,
                                 "final_score": i.sys_score})
        pages = (high_unprocessed // 10)

        if high_unprocessed % 10 != 0:
            pages = pages +1
        return JsonResponse({"msg": "success", "items": high_un_list, "pages": pages})

    # 高分已处理

    if library == 'high' and process == 'processed':
        high_list = []
        high_processeds = Comments.objects.filter(sys_score__gt=0.5, is_scored=1)
        for i in high_processeds[start:end]:
            high_list.append({"id": i.comment_id,"catch_time": i.catch_time,"comment_time": i.comment_time,
                              "final_score": i.sys_score})
        pages = (high_processed // 10)

        if high_processed % 10 != 0:
            pages = pages +1
        return JsonResponse({"msg": "success", "items": high_list, "pages": pages})


@csrf_exempt
def count1(request):
    comment_id = int(request.POST.get("comment_id"))
    comment = Comments.objects.get(comment_id = comment_id)
    low_comment = []
    low_comments = Comments.objects.filter(sys_score__lte = 0.5)
    for x in (low_comments):
        low_comment.append(x.comment_id)
    if comment.comment_id in low_comment:
        if comment.is_scored == 0:
            library = "low"
            process = "unprocessed"
            dic = {"msg" : "success", "library" : library, "process" : process, "comment_id" : comment_id}
            return HttpResponse(json.dumps(dic))
        else:
            library = "low"
            process = "processed"
            dic = {"msg" : "success", "library" : library, "process" : process, "comment_id" : comment_id}
            return HttpResponse(json.dumps(dic))

    else:
        if comment.is_scored == 0:
            library = "high"
            process = "unprocessed"
            dic = {"msg" : "success", "library" : library, "process" : process, "comment_id" : comment_id}
            return HttpResponse(json.dumps(dic))
        else:
            library = "high"
            process = "processed"
            dic = {"msg" : "success", "library" : library, "process" : process, "comment_id" : comment_id}
            return HttpResponse(json.dumps(dic))


@csrf_exempt
def comment_content(request):
    library = request.POST.get("library")
    comment_Id = str(request.POST.get("comment_id"))
    # 低分
    if library == 'low':
        comment = Comments.objects.get(comment_id=comment_Id)
        man = []
        manager = AuthUser.objects.filter()
        for x in manager:
            man.append(x.username)
        if not comment.arti_score and comment.is_scored == 0:
            arti_score="Null"
            dict2 = [{"manager" : man, "comment_id" : comment.comment_id , "catch_address" : comment.address,
                  "catch_time" : comment.catch_time,"comment_time" : comment.comment_time,
                  "sys_score" : comment.sys_score, "comment_content" : comment.content,
                  'arti_score' : arti_score}]
            return JsonResponse({"msg" : "success", "dic" : dict2})
        else:
            arti_score=comment.arti_score
            dict2 = [{"manager" : man, "comment_id" : comment.comment_id , "catch_address" : comment.address,
                  "catch_time" : comment.catch_time,"comment_time" : comment.comment_time,
                  "sys_score" : comment.sys_score, "comment_content" : comment.content,
                  'arti_score' : arti_score}]
            return JsonResponse({"msg" : "success", "dic" : dict2})

    # 高分
    if library == 'high':
        comment = Comments.objects.get(comment_id=comment_Id)
        man = []
        manager = AuthUser.objects.filter()
        for x in manager:
            man.append(x.username)
        if not comment.arti_score and comment.is_scored == 0:
            arti_score="Null"
            dict2 = [{"manager" : man, "comment_id" : comment.comment_id , "catch_address" : comment.address,
                  "catch_time" : comment.catch_time,"comment_time" : comment.comment_time,
                  "sys_score" : comment.sys_score, "comment_content" : comment.content,
                  'arti_score' : arti_score}]
            return JsonResponse({"msg" : "success", "dic" : dict2})
        else:
            arti_score=comment.arti_score
            dict2 = [{"manager" : man, "comment_id" : comment.comment_id , "catch_address" : comment.address,
                  "catch_time" : comment.catch_time,"comment_time" : comment.comment_time,
                  "sys_score" : comment.sys_score, "comment_content" : comment.content,
                  'arti_score' : arti_score}]
            return JsonResponse({"msg" : "success", "dic" : dict2})


# 人工评分
@csrf_exempt
def submit_newscore(request):
    comment_current_id = request.POST.get('comment_current_id')

templates/function/comment_list_high_processed.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>commen_list_low_unprocessed</title>
		<link rel="stylesheet" type="text/css" href="/static/css/nav.css" />
		<link rel="stylesheet" type="text/css" href="/static/css/comment_list.css" />
		<script src="http://code.jquery.com/jquery-2.1.1.min.js"></script>
		<script type="text/javascript" src="/static/js/comment_list.js"></script>
	</head>
	<body>
		<ul>
			<li><div class="title"><img src="/static/images/logo_nowords.png" id="logo">宝骏新能源评论预警系统</div></li>
			<li><a href="{% url 'function:index' %}">主页</a></li>
			<li><a href="{% url 'admin:index'%}">管理人员</a></li>
			<li style="float: right;padding-right: 30px;"><a href="{% url 'account:auth_logout' %}">退出登录</a></li>
		</ul>

		<div class="all">

			<div></div>
			<div class="current_comments">
				<table>
					<h3>高分库-已处理</h3>
					<thead>
						<tr>
							<th>编号</th>
							<th>抓取时间</th>
							<th>评论时间</th>
							<th>评分</th>
							<th>操作</th>
						</tr>
					</thead>
					    <tbody class="comment_list">
                            <a href="{% url 'function:comment_content_high_processed' %}" style="text-decoration: none;"></a>
                        </tbody>
				</table>
				<input type="button" class="page_up" value="上一页" onclick="page_up()" />
				<span id="page_current">1</span>/
				<span id="page_all"></span>
				<input type="button" class="page_down" value="下一页" onclick="page_down()" />
			</div>

		</div>
	</body>
</html>

templates/function/comment_list_high_unprocessed.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>commen_list_low_unprocessed</title>
		<link rel="stylesheet" type="text/css" href="/static/css/nav.css" />
		<link rel="stylesheet" type="text/css" href="/static/css/comment_list.css" />
		<script src="http://code.jquery.com/jquery-2.1.1.min.js"></script>
		<script type="text/javascript" src="/static/js/comment_list.js"></script>
	</head>
	<body>
		<ul>
			<li><div class="title"><img src="/static/images/logo_nowords.png" id="logo">宝骏新能源评论预警系统</div></li>
			<li><a href="{% url 'function:index' %}">主页</a></li>
			<li><a href="{% url 'admin:index'%}">管理人员</a></li>
			<li style="float: right;padding-right: 30px;"><a href="{% url 'account:auth_logout' %}">退出登录</a></li>
		</ul>
		
		<div class="all">

			<div></div>
			<div class="current_comments">
				<table>
					<h3>高分库-未处理</h3>
					<thead>
						<tr>
							<th>编号</th>
							<th>抓取时间</th>
							<th>评论时间</th>
							<th>评分</th>
							<th>操作</th>
						</tr>
					</thead>
					<tbody class="comment_list">
                    <a href="{% url 'function:comment_content_high_unprocessed' %}" style="text-decoration: none;"></a>
					</tbody>
				</table>
				<input type="button" class="page_up" value="上一页" onclick="page_up()" />
				<span id="page_current">1</span>/
				<span id="page_all"></span>
				<input type="button" class="page_down" value="下一页" onclick="page_down()" />
			</div>
			
		</div>
	</body>
</html>

templates/function/comment_list_low_processed.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>commen_list_low_unprocessed</title>
		<link rel="stylesheet" type="text/css" href="/static/css/nav.css" />
		<link rel="stylesheet" type="text/css" href="/static/css/comment_list.css" />
		<script src="http://code.jquery.com/jquery-2.1.1.min.js"></script>
		<script type="text/javascript" src="/static/js/comment_list.js"></script>
	</head>
	<body>
		<ul>
			<li><div class="title"><img src="/static/images/logo_nowords.png" id="logo">宝骏新能源评论预警系统</div></li>
			<li><a href="{% url 'function:index' %}">主页</a></li>
			<li><a href="{% url 'admin:index'%}">管理人员</a></li>
			<li style="float: right;padding-right: 30px;"><a href="{% url 'account:auth_logout' %}">退出登录</a></li>
		</ul>

		<div class="all">

			<div></div>
			<div class="current_comments">
				<table>
					<h3>低分库-已处理</h3>
					<thead>
						<tr>
							<th>编号</th>
							<th>抓取时间</th>
							<th>评论时间</th>
							<th>评分</th>
							<th>操作</th>
						</tr>
					</thead>
					<tbody class="comment_list">
                    <a href="{% url 'function:comment_content_low_processed' %}" style="text-decoration: none;"></a>
					</tbody>
				</table>
				<input type="button" class="page_up" value="上一页" onclick="page_up()" />
				<span id="page_current">1</span>/
				<span id="page_all"></span>
				<input type="button" class="page_down" value="下一页" onclick="page_down()" />
			</div>
			
		</div>
	</body>
</html>

templates/function/comment_list_low_unprocessed.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>comment_list_low_unprocessed</title>
		<link rel="stylesheet" type="text/css" href="/static/css/nav.css" />
		<link rel="stylesheet" type="text/css" href="/static/css/comment_list.css" />
		<script src="http://code.jquery.com/jquery-2.1.1.min.js"></script>
		<script type="text/javascript" src="/static/js/comment_list.js"></script>
	</head>
	<body>
		<ul>
			<li><div class="title"><img src="/static/images/logo_nowords.png" id="logo">宝骏新能源评论预警系统</div></li>
			<li><a href="{% url 'function:index' %}">主页</a></li>
			<li><a href="{% url 'admin:index'%}">管理人员</a></li>
			<li style="float: right;padding-right: 30px;"><a href="{% url 'account:auth_logout' %}">退出登录</a></li>
		</ul>
		
		<div class="all">

			<div></div>
			<div class="current_comments">
				<table>
					<h3>低分库-未处理</h3>
					<thead>
						<tr>
							<th>编号</th>
							<th>抓取时间</th>
							<th>评论时间</th>
							<th>评分</th>
							<th>操作</th>
						</tr>
					</thead>
					<tbody class="comment_list">
                    <a href="{% url 'function:comment_content_low_unprocessed' %}" style="text-decoration: none;"></a>
					</tbody>
				</table>
				<input type="button" class="page_up" value="上一页" onclick="page_up()" />
				<span id="page_current">1</span>/
				<span id="page_all"></span>
				<input type="button" class="page_down" value="下一页" onclick="page_down()" />
			</div>
			
		</div>
	</body>
</html>

templates/function/index.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta charset="utf-8" />
		<title>crawler_index</title>
		<link rel="stylesheet" type="text/css" href="/static/css/login&index.css" />
		<link rel="stylesheet" type="text/css" href="/static/css/nav.css" />
		<script src="http://code.jquery.com/jquery-2.1.1.min.js"></script>
		<script type="text/javascript" src="/static/js/index.js"></script>
	</head>
	<body>
        {% if user.is_authenticated %}
		<ul>
			<li><div class="title"><img src="/static/images/logo_nowords.png" id="logo">宝骏新能源评论预警系统</div></li>
			<li><a href="{% url 'function:index' %}">主页</a></li>
			<li><a href="{% url 'function:admin' %}">管理人员</a></li>
                    <li>
                        <a href="#">{{ user.username }}</a>
                    </li>
			<li style="float: right;padding-right: 30px;"><a href="{% url 'account:auth_logout' %}">退出登录</a></li>
		</ul>

		<div class="wrapper">
			<div class="low">
				<div class="index_m">
					<div class="index_boder">
						<div class="index_padding" id="index_model">
							<h2 class="score_classification">低分库</h2>
							<p class="data_display">
							<!--<a href="comment_list_low.html" style="text-decoration: none;"> -->
                            <a href="{% url 'function:low_unprocessed_list_html' %}" style="text-decoration: none;">
                            <span>待处理评论：</span>
							<span id="low_unprocessed"></span>
                            </a>
							</p>
							<br />
							<p class="data_display">
                            <a href="{% url 'function:low_processed_list_html' %}" style="text-decoration: none;">
							<span>已处理评论：</span>
							<span id="low_processed"></span>
                            </a>
							</p>
							<br /><br />
						</div>
					</div>
				</div>
			</div>

			<div class="high">
				<div class="index_m">
					<div class="index_boder">
						<div class="index_padding" id="index_model">
							<h2 class="score_classification">高分库</h2>
							<p class="data_display">
							<a href="{% url 'function:high_unprocessed_list_html' %}" style="text-decoration: none;">
							<span>待处理评论：</span>
							<span id="high_unprocessed"></span>
                            </a>
							</p>
							<br />
							<p class="data_display">
                            <a href="{% url 'function:high_processed_list_html' %}" style="text-decoration: none;">
							<span>已处理评论：</span>
							<span id="high_processed"></span>
							</a>
							</p>
							<br /><br />

						</div>
					</div>
				</div>
			</div>

            <div class="index_operation">
				<div class="index_op">
					<div class="index_bg">
						<div class="index_padding">
							<input type="button" value="保存并训练" class="btn" onclick="save_train()" />
							<input type="button" value="正确率" class="btn" onclick="show_accuracy()" />
							<input type="button" value="重新系统评分" class="btn" onclick="rejudge()" />
							<p id="info_display"></p>
						</div>
					</div>
				</div>
			</div>

		</div>
            {% else %}
                <br>
                <br>
                <p>你莫得访问权限，请先登录</p>
                <p><a href="{% url 'account:auth_login' %}">登录</a> </p>
    {% endif %}
	</body>
</html>